# this docker compose file is written only for development purposes
# its suit when u r trying to develop and add features to this service

services:
  
  homec:
    image: home
    container_name: homec
    restart: unless-stopped
    tty: true
    volumes:
      - type: bind
        src: ./src
        target: /app
    ports:
      - 3001:3001
