# this docker compose file is written only for development purposes
# its suit when u r trying to develop and add features to this service

services:
  
  homec:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homec
    restart: unless-stopped
    tty: true
    volumes:
      - type: bind
        source: ./src
        target: /app
    ports:
      - 3001:3001
